# Rustfmt configuration for RustLLM Core

# Use verbose diffs
# verbose is deprecated or expects string; disable
# verbose = true

# Stable features
edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
max_width = 100

# Imports
imports_granularity = "Module"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80
format_code_in_doc_comments = true

# Alignment and spacing
indent_style = "Block"
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Functions and impl blocks
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
fn_single_line = false
where_single_line = false

# Chains and expressions
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = true

# Error handling
overflow_delimited_expr = true
error_on_line_overflow = false
error_on_unformatted = false

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Strings
format_strings = true
hex_literal_case = "Lower"

# Attributes
reorder_impl_items = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
force_multiline_blocks = false
fn_args_layout = "Tall"
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50