[package]
name = "coeus-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Core numerical traits and execution primitives for Coeus."
[lib]
path = "src/lib.rs"

[dependencies]
mnemosyne = { workspace = true }
moirai    = { workspace = true }
hermes-simd = { workspace = true }
eunomia = { workspace = true }
bytemuck   = { workspace = true }
smallvec   = { workspace = true }
thiserror  = { workspace = true }
