pub mod activation;
pub mod conv;
pub mod linalg;
pub mod linear;
pub mod loss;
pub mod normalization;
pub mod ops;
pub mod pooling;
pub mod distance;

pub use activation::*;
pub use conv::*;
pub use linalg::*;
pub use linear::*;
pub use loss::*;
pub use normalization::*;
pub use ops::*;
pub use pooling::*;
pub use distance::*;

use pyo3::prelude::*;

pub fn register(_py: Python, m: &Bound<PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(linear::linear, m)?)?;
    m.add_function(wrap_pyfunction!(activation::relu, m)?)?;
    m.add_function(wrap_pyfunction!(activation::sigmoid, m)?)?;
    m.add_function(wrap_pyfunction!(activation::tanh, m)?)?;
    m.add_function(wrap_pyfunction!(activation::gelu, m)?)?;
    m.add_function(wrap_pyfunction!(activation::silu, m)?)?;
    m.add_function(wrap_pyfunction!(activation::leaky_relu, m)?)?;
    m.add_function(wrap_pyfunction!(activation::elu, m)?)?;
    m.add_function(wrap_pyfunction!(activation::softmax, m)?)?;
    m.add_function(wrap_pyfunction!(activation::log_softmax, m)?)?;
    m.add_function(wrap_pyfunction!(loss::mse_loss, m)?)?;
    m.add_function(wrap_pyfunction!(loss::cross_entropy, m)?)?;
    m.add_function(wrap_pyfunction!(loss::nll_loss, m)?)?;
    m.add_function(wrap_pyfunction!(loss::l1_loss, m)?)?;
    m.add_function(wrap_pyfunction!(loss::smooth_l1_loss, m)?)?;
    m.add_function(wrap_pyfunction!(loss::binary_cross_entropy, m)?)?;
    m.add_function(wrap_pyfunction!(loss::bce_with_logits_loss, m)?)?;
    m.add_function(wrap_pyfunction!(normalization::batch_norm, m)?)?;
    m.add_function(wrap_pyfunction!(normalization::layer_norm, m)?)?;
    m.add_function(wrap_pyfunction!(pooling::max_pool2d, m)?)?;
    m.add_function(wrap_pyfunction!(pooling::avg_pool2d, m)?)?;
    m.add_function(wrap_pyfunction!(ops::dropout, m)?)?;
    m.add_function(wrap_pyfunction!(conv::conv1d, m)?)?;
    m.add_function(wrap_pyfunction!(conv::conv2d, m)?)?;
    m.add_function(wrap_pyfunction!(conv::conv3d, m)?)?;
    m.add_function(wrap_pyfunction!(conv::conv_transpose1d, m)?)?;
    m.add_function(wrap_pyfunction!(conv::conv_transpose2d, m)?)?;
    m.add_function(wrap_pyfunction!(conv::conv_transpose3d, m)?)?;
    m.add_function(wrap_pyfunction!(ops::matmul, m)?)?;
    m.add_function(wrap_pyfunction!(ops::bmm, m)?)?;
    m.add_function(wrap_pyfunction!(ops::addmm, m)?)?;
    m.add_function(wrap_pyfunction!(ops::reshape, m)?)?;
    m.add_function(wrap_pyfunction!(ops::view, m)?)?;
    m.add_function(wrap_pyfunction!(ops::flatten, m)?)?;
    m.add_function(wrap_pyfunction!(ops::squeeze, m)?)?;
    m.add_function(wrap_pyfunction!(ops::unsqueeze, m)?)?;
    m.add_function(wrap_pyfunction!(ops::transpose, m)?)?;
    m.add_function(wrap_pyfunction!(ops::permute, m)?)?;
    m.add_function(wrap_pyfunction!(ops::mv, m)?)?;
    m.add_function(wrap_pyfunction!(ops::addr, m)?)?;
    m.add_function(wrap_pyfunction!(ops::outer, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::eig, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::eigh, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::matrix_exp, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::matrix_power, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::cholesky, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::qr, m)?)?;
    m.add_function(wrap_pyfunction!(linalg::svd, m)?)?;
    m.add_function(wrap_pyfunction!(distance::norm, m)?)?;
    m.add_function(wrap_pyfunction!(distance::pairwise_distance, m)?)?;
    m.add_function(wrap_pyfunction!(distance::cosine_similarity, m)?)?;
    m.add_function(wrap_pyfunction!(ops::gather, m)?)?;
    m.add_function(wrap_pyfunction!(ops::index_select, m)?)?;
    m.add_function(wrap_pyfunction!(ops::nonzero, m)?)?;
    m.add_function(wrap_pyfunction!(ops::index_add, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::cat, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::stack, m)?)?;

    // Math/Comparison/Logical from functions.rs for functional parity
    m.add_function(wrap_pyfunction!(crate::tensor::functions::isnan, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::isinf, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::isfinite, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::logical_and, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::logical_or, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::logical_xor, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::logical_not, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::atan2, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::sqrt, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::rsqrt, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::erf, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::erfc, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::erfinv, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::log1p, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::expm1, m)?)?;
    m.add_function(wrap_pyfunction!(crate::tensor::functions::reciprocal, m)?)?;

    Ok(())
}
