[package]
name = "coeus-autograd"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Automatic differentiation engine for Coeus tensor library"

[dependencies]
coeus-dtype = { path = "../dtype" }
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
rayon.workspace = true

[dev-dependencies]
approx = "0.5"
