//! Dense storage creation from vectors and other data sources

use storage::{DenseStorage, Result, Storage};
use dtype::DataType;
use alloc::{vec, vec::Vec};

/// Create dense storage from vector
///
/// # Arguments
/// * `data` - Vector of data elements
/// * `shape` - Shape dimensions
///
/// # Returns
/// Dense storage containing the data
///
/// # Examples
/// ```
/// use dense::creation::from_vec;
/// use dtype::float::Float32;
///
/// let data = vec![Float32::new(1.0), Float32::new(2.0), Float32::new(3.0), Float32::new(4.0)];
/// let storage = from_vec(data, &[2, 2]).unwrap();
/// // Creates 2x2 storage with the data
/// ```
pub fn from_vec<T: DataType>(data: Vec<T>, shape: &[usize]) -> Result<DenseStorage<T>> {
    DenseStorage::from_vec(data, shape)
}

/// Create dense storage from slice
///
/// # Arguments
/// * `data` - Slice of data elements
/// * `shape` - Shape dimensions
///
/// # Returns
/// Dense storage containing the data
///
/// # Examples
/// ```
/// use dense::creation::from_slice;
/// use dtype::float::Float32;
///
/// let data = [Float32::new(1.0), Float32::new(2.0), Float32::new(3.0), Float32::new(4.0)];
/// let storage = from_slice(&data, &[2, 2]).unwrap();
/// // Creates 2x2 storage with the data
/// ```
pub fn from_slice<T: DataType>(data: &[T], shape: &[usize]) -> Result<DenseStorage<T>>
where
    T: Clone,
{
    DenseStorage::from_vec(data.to_vec(), shape)
}

/// Create dense storage filled with constant value
///
/// # Arguments
/// * `shape` - Shape dimensions
/// * `value` - Value to fill storage with
///
/// # Returns
/// Dense storage filled with the constant value
///
/// # Examples
/// ```
/// use dense::creation::full;
/// use dtype::float::Float32;
///
/// let storage = full(&[2, 3], Float32::new(5.0)).unwrap();
/// // Creates 2x3 storage filled with 5.0
/// ```
pub fn full<T: DataType>(shape: &[usize], value: T) -> Result<DenseStorage<T>>
where
    T: Clone,
{
    let size = shape.iter().product();
    let data = vec![value; size];
    DenseStorage::from_vec(data, shape)
}

/// Create dense storage filled with constant value, matching another storage's shape
///
/// # Arguments
/// * `like` - Storage to match shape from
/// * `value` - Value to fill storage with
///
/// # Returns
/// Dense storage filled with the constant value with same shape as input
///
/// # Examples
/// ```
/// use dense::creation::{zeros, full_like};
/// use dtype::float::Float32;
///
/// let original = zeros::<Float32>(&[2, 3]).unwrap();
/// let filled = full_like(&original, Float32::new(7.0)).unwrap();
/// // Creates 2x3 storage filled with 7.0
/// ```
pub fn full_like<T: DataType>(like: &DenseStorage<T>, value: T) -> Result<DenseStorage<T>>
where
    T: Clone,
{
    full(like.shape().dims(), value)
}

/// Create dense storage from iterator
///
/// # Arguments
/// * `iter` - Iterator over data elements
/// * `shape` - Shape dimensions
///
/// # Returns
/// Dense storage containing the data from iterator
///
/// # Examples
/// ```
/// use dense::creation::from_iter;
/// use dtype::float::Float32;
///
/// let data = (1..=4).map(|x| Float32::new(x as f32));
/// let storage = from_iter(data, &[2, 2]).unwrap();
/// // Creates 2x2 storage with values 1.0, 2.0, 3.0, 4.0
/// ```
pub fn from_iter<T: DataType, I: Iterator<Item = T>>(
    iter: I,
    shape: &[usize],
) -> Result<DenseStorage<T>> {
    let data: Vec<T> = iter.collect();
    DenseStorage::from_vec(data, shape)
}

/// Create dense storage using a function
///
/// # Arguments
/// * `shape` - Shape dimensions
/// * `f` - Function that takes flat index and returns value
///
/// # Returns
/// Dense storage with values generated by the function
///
/// # Examples
/// ```
/// use dense::creation::from_fn;
/// use dtype::float::Float32;
///
/// let storage = from_fn(&[2, 2], |i| Float32::new(i as f32)).unwrap();
/// // Creates 2x2 storage with values 0.0, 1.0, 2.0, 3.0
/// ```
pub fn from_fn<T: DataType, F: Fn(usize) -> T>(
    shape: &[usize],
    f: F,
) -> Result<DenseStorage<T>> {
    let size = shape.iter().product();
    let data: Vec<T> = (0..size).map(f).collect();
    DenseStorage::from_vec(data, shape)
}

/// Create scalar storage with given value
///
/// # Arguments
/// * `value` - Scalar value
///
/// # Returns
/// Scalar dense storage containing the value
///
/// # Examples
/// ```
/// use dense::creation::scalar;
/// use dtype::float::Float32;
///
/// let scalar = scalar(Float32::new(42.0)).unwrap();
/// // Creates scalar storage with value 42.0
/// ```
pub fn scalar<T: DataType>(value: T) -> Result<DenseStorage<T>> {
    DenseStorage::from_vec(vec![value], &[])
}

#[cfg(test)]
mod tests {
    use super::*;
    use dtype::float::Float32;

    #[test]
    fn test_from_vec() {
        let data = vec![Float32::new(1.0), Float32::new(2.0), Float32::new(3.0), Float32::new(4.0)];
        let storage = from_vec(data.clone(), &[2, 2]).unwrap();
        assert_eq!(storage.as_slice(), data.as_slice());
        assert_eq!(storage.shape().dims(), &[2, 2]);
    }

    #[test]
    fn test_from_slice() {
        let data = [Float32::new(1.0), Float32::new(2.0), Float32::new(3.0), Float32::new(4.0)];
        let storage = from_slice(&data, &[2, 2]).unwrap();
        assert_eq!(storage.as_slice(), &data);
        assert_eq!(storage.shape().dims(), &[2, 2]);
    }

    #[test]
    fn test_full() {
        let storage = full(&[2, 3], Float32::new(5.0)).unwrap();
        let expected = vec![Float32::new(5.0); 6];
        assert_eq!(storage.as_slice(), expected.as_slice());
        assert_eq!(storage.shape().dims(), &[2, 3]);
    }

    #[test]
    fn test_full_like() {
        use crate::creation::zeros;
        let original = zeros::<Float32>(&[2, 3]).unwrap();
        let filled = full_like(&original, Float32::new(7.0)).unwrap();
        let expected = vec![Float32::new(7.0); 6];
        assert_eq!(filled.as_slice(), expected.as_slice());
        assert_eq!(filled.shape().dims(), &[2, 3]);
    }

    #[test]
    fn test_from_iter() {
        let data = (1..=4).map(|x| Float32::new(x as f32));
        let storage = from_iter(data, &[2, 2]).unwrap();
        let expected = vec![Float32::new(1.0), Float32::new(2.0), Float32::new(3.0), Float32::new(4.0)];
        assert_eq!(storage.as_slice(), expected.as_slice());
        assert_eq!(storage.shape().dims(), &[2, 2]);
    }

    #[test]
    fn test_from_fn() {
        let storage = from_fn(&[2, 2], |i| Float32::new(i as f32)).unwrap();
        let expected = vec![Float32::new(0.0), Float32::new(1.0), Float32::new(2.0), Float32::new(3.0)];
        assert_eq!(storage.as_slice(), expected.as_slice());
        assert_eq!(storage.shape().dims(), &[2, 2]);
    }

    #[test]
    fn test_scalar() {
        let scalar = scalar(Float32::new(42.0)).unwrap();
        assert_eq!(scalar.as_slice(), &[Float32::new(42.0)]);
        assert_eq!(scalar.shape().dims(), &[]);
    }
}