[package]
name = "storage"
description = "Memory storage abstractions for Coeus tensors"
readme = "README.md"
keywords = ["machine-learning", "deep-learning", "tensor", "storage"]
categories = ["science", "data-structures"]
documentation = "https://docs.rs/coeus-storage"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
dtype = { path = "../dtype" }
num-traits.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
approx.workspace = true
rand.workspace = true
criterion.workspace = true
coeus-sparse = { path = "../sparse" }