# pycoeus.pyi — Python type stub for the pycoeus extension module.
#
# This file provides type annotations for IDE completion, mypy checking,
# and documentation tools. It mirrors the public API of the pycoeus
# PyO3 extension module compiled from coeus-python.
#
# NOTE: This is a manually-maintained stub. When new functions or classes
# are added to lib.rs, update this file accordingly.

from __future__ import annotations

from typing import List, Optional, Sequence, Tuple, Union, overload

# ── Tensor ────────────────────────────────────────────────────────────────────

class Tensor:
    """N-dimensional tensor with optional autograd tracking."""

    shape: List[int]
    data: List[float]
    requires_grad: bool
    grad: Optional[List[float]]
    ndim: int
    is_training: bool

    def __init__(
        self,
        data: List[float],
        shape: Optional[List[int]] = None,
        requires_grad: bool = False,
    ) -> None: ...

    # Arithmetic operators
    #
    # The five binary operators (`+`, `-`, `*`, `/`, `@`) accept either a
    # `Tensor` (elementwise) or a Python `float` (scalar broadcast). This
    # matches PyTorch / JAX / MLX ergonomics: `t - 1.0`, `t / 2.0`, etc.
    @overload
    def __add__(self, other: Tensor) -> Tensor: ...
    @overload
    def __add__(self, other: float) -> Tensor: ...
    def __add__(self, other: Union[Tensor, float]) -> Tensor: ...
    @overload
    def __sub__(self, other: Tensor) -> Tensor: ...
    @overload
    def __sub__(self, other: float) -> Tensor: ...
    def __sub__(self, other: Union[Tensor, float]) -> Tensor: ...
    @overload
    def __mul__(self, other: Tensor) -> Tensor: ...
    @overload
    def __mul__(self, other: float) -> Tensor: ...
    def __mul__(self, other: Union[Tensor, float]) -> Tensor: ...
    @overload
    def __truediv__(self, other: Tensor) -> Tensor: ...
    @overload
    def __truediv__(self, other: float) -> Tensor: ...
    def __truediv__(self, other: Union[Tensor, float]) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __abs__(self) -> Tensor: ...
    def __pow__(self, exp: float, modulo: Optional[int] = None) -> Tensor: ...
    def __rmul__(self, scalar: float) -> Tensor: ...
    def __radd__(self, scalar: float) -> Tensor: ...
    def __rsub__(self, scalar: float) -> Tensor: ...
    def __rtruediv__(self, scalar: float) -> Tensor: ...
    def __rpow__(self, base: float, modulo: Optional[int] = None) -> Tensor: ...
    def __iadd__(self, other: Tensor) -> None: ...
    def __isub__(self, other: Tensor) -> None: ...
    def __imul__(self, other: Tensor) -> None: ...

    # Indexing
    @overload
    def __getitem__(self, index: int) -> Tensor: ...
    @overload
    def __getitem__(self, index: slice) -> Tensor: ...
    def __setitem__(self, index: int, value: Union[float, Tensor]) -> None: ...
    def __iter__(self) -> TensorIterator: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    # Comparison operators (return float tensors: 1.0/0.0)
    def eq(self, other: Tensor) -> Tensor: ...
    def lt(self, other: Tensor) -> Tensor: ...
    def gt(self, other: Tensor) -> Tensor: ...
    def le(self, other: Tensor) -> Tensor: ...
    def ge(self, other: Tensor) -> Tensor: ...
    def ne(self, other: Tensor) -> Tensor: ...

    # Math methods
    def exp(self) -> Tensor: ...
    def log(self) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def abs(self) -> Tensor: ...
    def neg(self) -> Tensor: ...
    def recip(self) -> Tensor: ...
    def sign(self) -> Tensor: ...
    def floor(self) -> Tensor: ...
    def ceil(self) -> Tensor: ...
    def round(self) -> Tensor: ...
    def trunc(self) -> Tensor: ...
    def sin(self) -> Tensor: ...
    def cos(self) -> Tensor: ...
    def pow(self, exp: float) -> Tensor: ...
    def clamp(self, min_val: float, max_val: float) -> Tensor: ...
    def scale(self, s: float) -> Tensor: ...

    # Reductions
    def sum_axis(self, axis: int, keepdim: bool = False) -> Tensor: ...
    def mean_axis(self, axis: int, keepdim: bool = False) -> Tensor: ...
    def sum(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def max_axis(self, axis: int) -> Tensor: ...
    def min_axis(self, axis: int) -> Tensor: ...
    def log_sum_exp(self, axis: int) -> Tensor: ...
    def cumsum(self, dim: int) -> Tensor: ...
    def softmax(self, dim: int) -> Tensor: ...
    def log_softmax(self, dim: int) -> Tensor: ...

    # Shape ops
    def reshape(self, shape: List[int]) -> Tensor: ...
    def view(self, shape: List[int]) -> Tensor: ...
    def permute(self, dims: List[int]) -> Tensor: ...
    def t(self) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def squeeze(self, axis: Optional[int] = None) -> Tensor: ...
    def unsqueeze(self, axis: int) -> Tensor: ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def expand(self, shape: List[int]) -> Tensor: ...
    def broadcast_to(self, shape: List[int]) -> Tensor: ...
    def repeat(self, reps: List[int]) -> Tensor: ...
    def flip(self, axis: int) -> Tensor: ...
    @property
    def T(self) -> Tensor: ...

    # Utility
    def item(self) -> float: ...
    def numel(self) -> int: ...
    def is_contiguous(self) -> bool: ...
    def tolist(self) -> List[float]: ...
    def clone_tensor(self) -> Tensor: ...
    def detach(self) -> Tensor: ...
    def requires_grad_(self, requires_grad: bool) -> Tensor: ...
    def zero_grad(self) -> None: ...
    def backward(self) -> None: ...

    # In-place
    def fill_(self, value: float) -> Tensor: ...
    def zero_(self) -> Tensor: ...
    def one_(self) -> Tensor: ...

    # Dtype casts
    def float(self) -> Tensor: ...
    def double(self) -> Tensor: ...
    def long(self) -> Tensor: ...
    def int(self) -> Tensor: ...
    def half(self) -> Tensor: ...
    def to(self, dtype: str) -> Tensor: ...
    def type_as(self, other: Tensor) -> Tensor: ...

class TensorIterator:
    def __iter__(self) -> TensorIterator: ...
    def __next__(self) -> Tensor: ...

class ComplexTensor:
    shape: List[int]
    data: List[Tuple[float, float]]
    real: List[float]
    imag: List[float]
    def __repr__(self) -> str: ...

# ── Constructors ──────────────────────────────────────────────────────────────

def zeros(shape: List[int], requires_grad: bool = False) -> Tensor: ...
def ones(shape: List[int], requires_grad: bool = False) -> Tensor: ...
def full(shape: List[int], value: float, requires_grad: bool = False) -> Tensor: ...
def arange(start: float, end: float, step: float = 1.0) -> Tensor: ...
def linspace(start: float, end: float, steps: int) -> Tensor: ...
def logspace(start: float, end: float, steps: int, base: float = 10.0) -> Tensor: ...
def geomspace(start: float, end: float, steps: int) -> Tensor: ...
def randn(shape: List[int], requires_grad: bool = False) -> Tensor: ...
def rand(shape: List[int], requires_grad: bool = False) -> Tensor: ...
def randint(
    low: int, high: int, shape: List[int], requires_grad: bool = False
) -> Tensor: ...
def bernoulli(
    shape: List[int], p: float = 0.5, requires_grad: bool = False
) -> Tensor: ...
def zeros_like(input: Tensor, requires_grad: bool = False) -> Tensor: ...
def ones_like(input: Tensor, requires_grad: bool = False) -> Tensor: ...
def eye(n: int, requires_grad: bool = False) -> Tensor: ...

# ── Functional ops ────────────────────────────────────────────────────────────

def sum(input: Tensor) -> Tensor: ...
def mean(input: Tensor) -> Tensor: ...
def sum_axis(input: Tensor, axis: int, keepdim: bool = False) -> Tensor: ...
def mean_axis(input: Tensor, axis: int, keepdim: bool = False) -> Tensor: ...
def max_axis(input: Tensor, axis: int) -> Tensor: ...
def min_axis(input: Tensor, axis: int) -> Tensor: ...
def amax(input: Tensor) -> float: ...
def amin(input: Tensor) -> float: ...
def prod(input: Tensor) -> Tensor: ...
def log_sum_exp(input: Tensor, axis: int) -> Tensor: ...
def argmax(input: Tensor, dim: int) -> Tensor: ...
def argmin(input: Tensor, dim: int) -> Tensor: ...
def topk(
    input: Tensor, k: int, dim: int = 0, largest: bool = True
) -> Tuple[Tensor, Tensor]: ...
def sort(
    input: Tensor, dim: int = 0, descending: bool = False
) -> Tuple[Tensor, Tensor]: ...
def normalize(
    input: Tensor, p: float = 2.0, dim: int = 1, eps: float = 1e-12
) -> Tensor: ...
def isclose(a: Tensor, b: Tensor, rtol: float = 1e-5, atol: float = 1e-8) -> Tensor: ...
def allclose(a: Tensor, b: Tensor, rtol: float = 1e-5, atol: float = 1e-8) -> bool: ...
def nan_to_num(
    input: Tensor,
    nan: float = 0.0,
    posinf: Optional[float] = None,
    neginf: Optional[float] = None,
) -> Tensor: ...

# Element-wise
def abs(input: Tensor) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def erf(input: Tensor) -> Tensor: ...
def erfc(input: Tensor) -> Tensor: ...
def gammaln(input: Tensor) -> Tensor: ...
def lgamma(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def neg(input: Tensor) -> Tensor: ...
def recip(input: Tensor) -> Tensor: ...
def sign(input: Tensor) -> Tensor: ...
def floor(input: Tensor) -> Tensor: ...
def ceil(input: Tensor) -> Tensor: ...
def round(input: Tensor) -> Tensor: ...
def trunc(input: Tensor) -> Tensor: ...
def sin(input: Tensor) -> Tensor: ...
def cos(input: Tensor) -> Tensor: ...
def pow(input: Tensor, exp: float) -> Tensor: ...
def remainder(a: Tensor, b: Tensor) -> Tensor: ...
def maximum(a: Tensor, b: Tensor) -> Tensor: ...
def minimum(a: Tensor, b: Tensor) -> Tensor: ...
def tan(input: Tensor) -> Tensor: ...
def asin(input: Tensor) -> Tensor: ...
def acos(input: Tensor) -> Tensor: ...
def atan(input: Tensor) -> Tensor: ...
def sinh(input: Tensor) -> Tensor: ...
def cosh(input: Tensor) -> Tensor: ...
def tanh_direct(input: Tensor) -> Tensor: ...
def atanh(input: Tensor) -> Tensor: ...
def asinh(input: Tensor) -> Tensor: ...
def acosh(input: Tensor) -> Tensor: ...
def log2(input: Tensor) -> Tensor: ...
def log10(input: Tensor) -> Tensor: ...
def log1p(input: Tensor) -> Tensor: ...
def exp2(input: Tensor) -> Tensor: ...
def expm1(input: Tensor) -> Tensor: ...
def selu(input: Tensor) -> Tensor: ...
def clamp(input: Tensor, min_val: float, max_val: float) -> Tensor: ...
def scalar_mul(input: Tensor, scalar: float) -> Tensor: ...
def scalar_add(input: Tensor, scalar: float) -> Tensor: ...
def scalar_div(input: Tensor, scalar: float) -> Tensor: ...
def scalar_sub(input: Tensor, scalar: float) -> Tensor: ...
def fft(input: Tensor) -> ComplexTensor: ...
def ifft(input: ComplexTensor) -> Tensor: ...
def fft_energy(input: Tensor) -> Tensor: ...

# Linear algebra
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def bmm(a: Tensor, b: Tensor) -> Tensor: ...
def outer(a: Tensor, b: Tensor) -> Tensor: ...
def dot(input: Tensor, tensor: Tensor) -> Tensor: ...
def cross(input: Tensor, other: Tensor, dim: int = 0) -> Tensor: ...
def norm(input: Tensor) -> Tensor: ...
def vector_norm(
    input: Tensor, ord: float = 2.0, axis: Optional[int] = None, keepdim: bool = False
) -> Tensor: ...
def matrix_norm(input: Tensor, ord: str = "fro") -> Union[float, Tensor]: ...
def einsum(subscript: str, operands: List[Tensor]) -> Tensor: ...

# Shape ops
def reshape(input: Tensor, shape: List[int]) -> Tensor: ...
def permute(input: Tensor, dims: List[int]) -> Tensor: ...
def t(input: Tensor) -> Tensor: ...
def squeeze(input: Tensor, dim: Optional[int] = None) -> Tensor: ...
def unsqueeze(input: Tensor, dim: int) -> Tensor: ...
def flatten(input: Tensor, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
def cat(tensors: List[Tensor], dim: int = 0) -> Tensor: ...
def stack(tensors: List[Tensor], dim: int = 0) -> Tensor: ...
def split(input: Tensor, chunk_size: int, dim: int) -> List[Tensor]: ...
def chunk(input: Tensor, chunks: int, dim: int = 0) -> List[Tensor]: ...
def flip(input: Tensor, axis: int) -> Tensor: ...
def roll(input: Tensor, shifts: List[int], dims: List[int]) -> Tensor: ...
def tril(input: Tensor, k: int = 0) -> Tensor: ...
def triu(input: Tensor, k: int = 0) -> Tensor: ...
def pad(input: Tensor, pads: List[Tuple[int, int]], value: float = 0.0) -> Tensor: ...
def repeat_interleave(input: Tensor, repeats: int, dim: int) -> Tensor: ...
def tile(input: Tensor, reps: List[int]) -> Tensor: ...
def broadcast_to(input: Tensor, shape: List[int]) -> Tensor: ...
def broadcast_tensors(tensors: List[Tensor]) -> List[Tensor]: ...
def meshgrid(tensors: List[Tensor], indexing: str = "ij") -> List[Tensor]: ...

# Selection / indexing
def gather(input: Tensor, dim: int, index: Tensor) -> Tensor: ...
def index_select(input: Tensor, dim: int, index: Tensor) -> Tensor: ...
def index_put(
    input: Tensor, indices: Tensor, values: Tensor, accumulate: bool = False
) -> Tensor: ...
def scatter_add(input: Tensor, dim: int, index: Tensor, src: Tensor) -> Tensor: ...
def masked_fill(input: Tensor, mask: Tensor, value: float) -> Tensor: ...
def masked_select(input: Tensor, mask: Tensor) -> Tensor: ...
def where_cond(cond: Tensor, on_true: Tensor, on_false: Tensor) -> Tensor: ...
def where_fn(cond: Tensor, on_true: Tensor, on_false: Tensor) -> Tensor: ...
def nonzero(input: Tensor) -> Tensor: ...
def one_hot(indices: Tensor, num_classes: int) -> Tensor: ...
def cumsum(input: Tensor, dim: int) -> Tensor: ...
def cumprod(input: Tensor, dim: int) -> Tensor: ...
def nansum(input: Tensor) -> Tensor: ...
def nanmean(input: Tensor) -> Tensor: ...
def diag(v: Tensor, k: int = 0) -> Tensor: ...
def diagonal(m: Tensor, k: int = 0) -> Tensor: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def log_softmax(input: Tensor, axis: int) -> Tensor: ...

# Statistical ops
def std(
    input: Tensor,
    unbiased: bool = True,
    axis: Optional[int] = None,
    keepdim: bool = False,
) -> Tensor: ...
def var(
    input: Tensor,
    unbiased: bool = True,
    axis: Optional[int] = None,
    keepdim: bool = False,
) -> Tensor: ...
def var_mean(
    input: Tensor,
    unbiased: bool = True,
    axis: Optional[int] = None,
    keepdim: bool = False,
) -> Tuple[Tensor, Tensor]: ...
def std_mean(
    input: Tensor,
    unbiased: bool = True,
    axis: Optional[int] = None,
    keepdim: bool = False,
) -> Tuple[Tensor, Tensor]: ...

# Gradient utilities
def clip_grad_norm_(
    parameters: List[Tensor], max_norm: float, norm_type: float = 2.0
) -> float: ...
def clip_grad_value_(parameters: List[Tensor], clip_value: float) -> None: ...

# ── Activations ───────────────────────────────────────────────────────────────

def relu(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def gelu(input: Tensor) -> Tensor: ...
def gelu_tanh(input: Tensor) -> Tensor: ...
def silu(input: Tensor) -> Tensor: ...
def mish(input: Tensor) -> Tensor: ...
def elu(input: Tensor) -> Tensor: ...
def softplus(input: Tensor) -> Tensor: ...
def leaky_relu(input: Tensor, negative_slope: float = 0.01) -> Tensor: ...
def glu(input: Tensor, dim: int = -1) -> Tensor: ...
def masked_softmax(input: Tensor, mask: Tensor, dim: int = -1) -> Tensor: ...
def causal_softmax(input: Tensor, dim: int = -1) -> Tensor: ...

# Functional aliases (F.*)
def f_softmax(input: Tensor, dim: int) -> Tensor: ...
def f_log_softmax(input: Tensor, dim: int) -> Tensor: ...
def f_relu(input: Tensor) -> Tensor: ...
def f_sigmoid(input: Tensor) -> Tensor: ...
def f_tanh(input: Tensor) -> Tensor: ...
def f_gelu(input: Tensor) -> Tensor: ...
def f_silu(input: Tensor) -> Tensor: ...
def f_mse_loss(input: Tensor, target: Tensor) -> Tensor: ...
def f_binary_cross_entropy(input: Tensor, target: Tensor) -> Tensor: ...
def f_cross_entropy(input: Tensor, targets: List[int]) -> Tensor: ...

# ── Loss functions ────────────────────────────────────────────────────────────

def mse_loss(input: Tensor, target: Tensor) -> Tensor: ...
def cross_entropy_loss(input: Tensor, targets: List[int]) -> Tensor: ...
def binary_cross_entropy(input: Tensor, target: Tensor) -> Tensor: ...
def nll_loss(input: Tensor, targets: List[int]) -> Tensor: ...
def l1_loss(input: Tensor, target: Tensor) -> Tensor: ...
def bce_with_logits(input: Tensor, target: Tensor) -> Tensor: ...
def poisson_nll(input: Tensor, target: Tensor) -> Tensor: ...
def soft_margin(input: Tensor, target: Tensor) -> Tensor: ...
def huber_loss(input: Tensor, target: Tensor, delta: float = 1.0) -> Tensor: ...
def kl_divergence(input: Tensor, target: Tensor) -> Tensor: ...
def margin_ranking_loss(
    input1: Tensor, input2: Tensor, target: List[float], margin: float = 0.0
) -> Tensor: ...
def cosine_embedding_loss(input1: Tensor, input2: Tensor, label: Tensor) -> Tensor: ...
def smooth_l1_loss(input: Tensor, target: Tensor, beta: float = 1.0) -> Tensor: ...
def cosine_similarity(
    input1: Tensor, input2: Tensor, dim: int = 1, eps: float = 1e-8
) -> Tensor: ...
def hinge_embedding_loss(
    input: Tensor, target: List[float], margin: float = 1.0
) -> Tensor: ...
def multi_label_soft_margin_loss(input: Tensor, target: Tensor) -> Tensor: ...
def gaussian_nll_loss(
    input: Tensor, target: Tensor, var: Tensor, full: bool = False
) -> Tensor: ...
def multi_label_margin_loss(input: Tensor, target: List[int]) -> Tensor: ...

# ── Attention ─────────────────────────────────────────────────────────────────

def scaled_dot_product_attention(
    query: Tensor,
    key: Tensor,
    value: Tensor,
    key_padding_mask: Optional[Tensor] = None,
    scale: Optional[float] = None,
    is_causal: bool = False,
) -> Tensor: ...

# ── nn modules ────────────────────────────────────────────────────────────────

class Module:
    is_training: bool
    def __init__(self) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def train(self, mode: bool = True) -> None: ...
    def eval(self) -> None: ...

class Linear:
    weight: Tensor
    bias: Optional[Tensor]
    def __init__(
        self, in_features: int, out_features: int, bias: bool = True
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class LayerNorm:
    weight: Tensor
    bias: Tensor
    eps: float
    def __init__(self, normalized_shape: int, eps: float = 1e-5) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def forward_nd(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class RMSNorm:
    weight: Tensor
    def __init__(self, normalized_shape: int, eps: float = 1e-6) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class Dropout:
    p: float
    is_training: bool
    def __init__(self, p: float = 0.5, training: bool = False) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class MaxPool1d:
    kernel_size: int
    stride: int
    padding: int
    dilation: int
    def __init__(
        self,
        kernel_size: int,
        stride: Optional[int] = None,
        padding: int = 0,
        dilation: int = 1,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def state_dict(self) -> StateDict: ...
    def zero_grad(self) -> None: ...

class AvgPool1d:
    kernel_size: int
    stride: int
    padding: int
    dilation: int
    def __init__(
        self,
        kernel_size: int,
        stride: Optional[int] = None,
        padding: int = 0,
        dilation: int = 1,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def state_dict(self) -> StateDict: ...
    def zero_grad(self) -> None: ...

class MaxPool2d:
    kernel_size: int
    stride: int
    padding: int
    dilation: int
    def __init__(
        self,
        kernel_size: int,
        stride: Optional[int] = None,
        padding: int = 0,
        dilation: int = 1,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class AvgPool2d:
    kernel_size: int
    stride: int
    padding: int
    dilation: int
    def __init__(
        self,
        kernel_size: int,
        stride: Optional[int] = None,
        padding: int = 0,
        dilation: int = 1,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class MaxPool3d:
    kernel_size: int
    stride: int
    padding: int
    dilation: int
    def __init__(
        self,
        kernel_size: int,
        stride: Optional[int] = None,
        padding: int = 0,
        dilation: int = 1,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class AvgPool3d:
    kernel_size: int
    stride: int
    padding: int
    dilation: int
    def __init__(
        self,
        kernel_size: int,
        stride: Optional[int] = None,
        padding: int = 0,
        dilation: int = 1,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class BatchNorm1d:
    weight: Tensor
    bias: Tensor
    running_mean: Tensor
    running_var: Tensor
    num_features: int
    eps: float
    momentum: float
    def __init__(
        self, num_features: int, eps: float = 1e-5, momentum: float = 0.1
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def eval_forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class BatchNorm2d:
    weight: Tensor
    bias: Tensor
    running_mean: Tensor
    running_var: Tensor
    num_features: int
    eps: float
    momentum: float
    def __init__(
        self, num_features: int, eps: float = 1e-5, momentum: float = 0.1
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def eval_forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class BatchNorm3d:
    weight: Tensor
    bias: Tensor
    running_mean: Tensor
    running_var: Tensor
    num_features: int
    eps: float
    momentum: float
    def __init__(
        self, num_features: int, eps: float = 1e-5, momentum: float = 0.1
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def eval_forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class GroupNorm:
    weight: Tensor
    bias: Tensor
    num_groups: int
    num_channels: int
    eps: float
    def __init__(
        self, num_groups: int, num_channels: int, eps: float = 1e-5
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class InstanceNorm1d:
    weight: Tensor
    bias: Tensor
    num_features: int
    eps: float
    def __init__(self, num_features: int, eps: float = 1e-5) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class InstanceNorm2d:
    weight: Tensor
    bias: Tensor
    num_features: int
    eps: float
    def __init__(self, num_features: int, eps: float = 1e-5) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class InstanceNorm3d:
    weight: Tensor
    bias: Tensor
    num_features: int
    eps: float
    def __init__(self, num_features: int, eps: float = 1e-5) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> StateDict: ...
    def load_state_dict(self, state_dict: StateDict) -> None: ...

class Embedding:
    weight: Tensor
    padding_idx: Optional[int]
    def __init__(
        self, num_embeddings: int, embedding_dim: int, padding_idx: Optional[int] = None
    ) -> None: ...
    def forward(self, indices: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...

class EmbeddingBag:
    weight: Tensor
    num_embeddings: int
    embedding_dim: int
    mode: str
    def __init__(
        self, num_embeddings: int, embedding_dim: int, mode: str = "sum"
    ) -> None: ...
    def forward(self, indices: Tensor, offsets: Optional[Tensor] = None) -> Tensor: ...
    def forward_with_offsets(
        self, indices: List[int], offsets: Optional[List[int]] = None
    ) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...

class Sequential:
    def __init__(self, modules: List[object]) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def append(self, module: object) -> None: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...

class ModuleList:
    def __init__(self, modules: Optional[List[object]] = None) -> None: ...
    def append(self, module: object) -> None: ...
    def extend(self, modules: List[object]) -> None: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...
    def __setitem__(self, index: int, module: object) -> None: ...

class MultiHeadAttention:
    d_model: int
    num_heads: int
    def __init__(self, d_model: int, num_heads: int = 8, bias: bool = True) -> None: ...
    def forward(
        self, input: Tensor, key_padding_mask: Optional[Tensor] = None
    ) -> Tensor: ...
    def forward_cross(
        self,
        query: Tensor,
        key: Tensor,
        value: Tensor,
        key_padding_mask: Optional[Tensor] = None,
    ) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...

class ScaledDotProductAttention:
    scale: Optional[float]
    is_causal: bool
    def __init__(
        self, scale: Optional[float] = None, is_causal: bool = False
    ) -> None: ...
    def forward(
        self,
        query: Tensor,
        key: Tensor,
        value: Tensor,
        key_padding_mask: Optional[Tensor] = None,
    ) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...

class LSTMCell:
    w_ih: Tensor
    b_ih: Optional[Tensor]
    w_hh: Tensor
    b_hh: Optional[Tensor]
    def __init__(
        self, input_size: int, hidden_size: int, bias: bool = True
    ) -> None: ...
    def step(self, x: Tensor, h: Tensor, c: Tensor) -> Tuple[Tensor, Tensor]: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...

class GRUCell:
    w_ih: Tensor
    b_ih: Optional[Tensor]
    w_hh: Tensor
    b_hh: Optional[Tensor]
    def __init__(
        self, input_size: int, hidden_size: int, bias: bool = True
    ) -> None: ...
    def step(self, x: Tensor, h: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...

# ── Optimizer ─────────────────────────────────────────────────────────────────

class SGD:
    lr: float
    def __init__(
        self,
        parameters: List[Tensor],
        lr: float = 0.01,
        momentum: float = 0.0,
        weight_decay: float = 0.0,
    ) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Adam:
    lr: float
    def __init__(
        self,
        parameters: List[Tensor],
        lr: float = 0.001,
        betas: Tuple[float, float] = (0.9, 0.999),
        eps: float = 1e-8,
        weight_decay: float = 0.0,
    ) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class AdamW:
    lr: float
    def __init__(
        self,
        parameters: List[Tensor],
        lr: float = 0.001,
        betas: Tuple[float, float] = (0.9, 0.999),
        eps: float = 1e-8,
        weight_decay: float = 0.01,
    ) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class LrScheduler:
    @staticmethod
    def step_decay(
        optimizer: object, base_lr: float, step_size: int, gamma: float
    ) -> LrScheduler: ...
    @staticmethod
    def cosine_anneal(
        optimizer: object, base_lr: float, t_max: int, eta_min: float
    ) -> LrScheduler: ...
    @staticmethod
    def linear_warmup(
        optimizer: object, base_lr: float, warmup_steps: int
    ) -> LrScheduler: ...
    @staticmethod
    def warmup_cosine(
        optimizer: object, base_lr: float, warmup_steps: int, t_max: int, eta_min: float
    ) -> LrScheduler: ...
    def step(self) -> None: ...

# ── State dict / checkpoint ───────────────────────────────────────────────────

class StateDict:
    def __init__(self) -> None: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...

# ── Context managers ──────────────────────────────────────────────────────────

class no_grad:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

# ── Utilities ─────────────────────────────────────────────────────────────────

def shutdown() -> None: ...
def layer_norm(
    input: Tensor,
    norm_shape: int,
    weight: Optional[Tensor] = None,
    bias: Optional[Tensor] = None,
    eps: float = 1e-5,
) -> Tensor: ...
def group_norm(
    input: Tensor,
    num_groups: int,
    weight: Optional[Tensor] = None,
    bias: Optional[Tensor] = None,
    eps: float = 1e-5,
) -> Tensor: ...
def linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None) -> Tensor: ...
def bilinear(
    input1: Tensor, input2: Tensor, weight: Tensor, bias: Optional[Tensor] = None
) -> Tensor: ...
def dropout(input: Tensor, p: float = 0.5, training: bool = False) -> Tensor: ...
def interpolate(input: Tensor, size: List[int], mode: str = "nearest") -> Tensor: ...
