[package]
name = "coeus-ops"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
coeus-core   = { workspace = true }
coeus-tensor = { workspace = true }
coeus-sparse = { workspace = true }
coeus-leto   = { path = "../coeus-leto" }
leto-ops     = { workspace = true }
smallvec     = { workspace = true }
num-traits   = { workspace = true }
thiserror    = { workspace = true }
half         = { workspace = true }
bytemuck     = { workspace = true }
melinoe      = { path = "../../melinoe", version = "0.7.0" }
