[package]
name = "coeus-nn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Neural-network layers and operators for Coeus."

[dependencies]
coeus-core     = { workspace = true }
coeus-tensor   = { workspace = true }
coeus-autograd = { workspace = true, default-features = false }
coeus-ops      = { workspace = true, default-features = false }
coeus-leto     = { version = "0.9.0", path = "../coeus-leto" }
smallvec       = { workspace = true }
thiserror      = { workspace = true }

[dev-dependencies]
coeus-autograd = { workspace = true, default-features = false }
coeus-ops      = { workspace = true, default-features = false }
coeus-optim    = { path = "../coeus-optim" }
criterion      = { workspace = true }

[[bench]]
name = "nn_bench"
path = "benches/nn_bench.rs"
harness = false
