[package]
name = "coeus-optim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
coeus-core     = { workspace = true }
coeus-ops      = { workspace = true, default-features = false }
coeus-tensor   = { workspace = true }
coeus-autograd = { workspace = true, default-features = false }
thiserror      = { workspace = true }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "optim_bench"
path = "benches/optim_bench.rs"
harness = false

